[package]
name = "legalis-us"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "United States jurisdiction support for Legalis-RS (Common Law)"
repository = "https://github.com/cool-japan/legalis"
homepage = "https://github.com/cool-japan/legalis"
documentation = "https://docs.rs/legalis-us"

[dependencies]
legalis-core.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
